version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: route4ssm
      POSTGRES_USER: route4ssm
      POSTGRES_PASSWORD: route4ssm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U route4ssm"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  hanko-migrate:
    image: ghcr.io/teamhanko/hanko:latest
    command: migrate up --config /config/config.yaml
    volumes:
      - ./hanko/config.yaml:/config/config.yaml
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  hanko:
    image: ghcr.io/teamhanko/hanko:latest
    command: serve all --config /config/config.yaml
    ports:
      - "8000:8000"
    volumes:
      - ./hanko/config.yaml:/config/config.yaml
    depends_on:
      postgres:
        condition: service_healthy
      hanko-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/hanko", "isready", "public", "--config", "/config/config.yaml"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: 